config/routes.rb
RateProgrammerTools::Application.routes.draw do

	root :to => 'home#index'
	match 'home/search' => 'home#search'

	namespace :user do	
		get 'activate/:activation_token' => 'users#activate', as: :activate
		get 'resend_activation/:username' => 'users#resend_activation', as: :resend_activation

	  get  'forgot_password'  => 'reset_password#new'
	  post 'forgot_password'  => 'reset_password#create'
	  get  'reset_password/:reset_token' => 'reset_password#edit', as: :reset_password
	  put  'reset_password' =>  'reset_password#update', as: :update_password

		get   'login'  => 'login#new'
		post  'login'  => 'login#create'
		match 'logout' => 'login#destroy'
	end
	resource :user, only: [:new,:create,:update] do 
		collection do
			get '/' => 'users#index'
			get 'profile/:username' => 'users#show', as: :show
			get 'settings' => 'users#edit', as: :edit      

			match  'signup' => 'users#new'
		end
	end

end

app/views/shared/_flash_messages.html.erb
<% if flash.count > 0 %>
    <div id="flash_messages" >
      <div id="content">
        <% flash.each do |type, message| %>
            <div class="alert <%= bootstrap_class_for_flash(type) %> fade in">
              <button class="close" data-dismiss="alert">×</button>
              <%= message.html_safe %>
            </div>
        <% end %>
      </div>
    </div>
<% end %>

app/views/shared/_user_menu.html.haml
- if	current_user
	.btn-group
		%a.btn.btn-primary{:href => show_user_path(current_user)}
			%i.icon-user.icon-white
			= " #{current_user.username}"
		%a.btn.btn-primary.dropdown-toggle{"data-toggle" => "dropdown"}
			%span.caret
		%ul.dropdown-menu
			%li
				%a{:href => show_user_path(current_user)}
					%i.icon-list-alt
					Profile
			%li
				%a{:href => edit_user_path}
					%i.icon-pencil
					Settings
			%li
				%a{:href => '#'}
					%i.icon-plus-sign
					Request Tool
			%li.divider
			%li
				%a{:href => user_logout_path}
					%i.icon-off
					Logout
- else
	= link_to 'Log In', user_login_path, {class: 'btn'}
	= link_to 'Sign Up', signup_user_path, {class: 'btn'}